spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luizalabs
    username: root
    password: teste123
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379