spring:
  datasource:
    url: jdbc:mysql://mysql:3306/luizalabs
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379