name: Build and Test Project

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Maven Build
        run: LuizaLabs-API/mvn package

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: luiza-labs-api
          path: LuizaLabs-API/target/*.jar